name: "SSH over WireGuard beta"
description: "SSH to your private servers over WireGuard VPN."
branding:
  icon: "lock"
  color: "purple"
inputs:
  user:
    description: "The user to connect as"
    required: true
  port:
    description: "The port to connect to"
    required: true
  host:
    description: "The host to connect to"
    required: true
  key:
    description: "The private key to use for authentication"
    required: true
  conf:
    description: "The Wireguard configuration file"
    required: true
  script:
    description: "The script to run"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/runner.sh
      shell: bash
      env:
        SSH_USER: ${{ inputs.user }}
        SSH_PORT: ${{ inputs.port }}
        SSH_HOST: ${{ inputs.host }}
        SSH_KEY: ${{ inputs.key }}
        WIREGUARD_CONFIG: ${{ inputs.conf }}
        SSH_SCRIPT: ${{ inputs.script }}
